// <auto-generated />
using System;
using BarkodSepetim.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarkodSepetim.Api.Migrations
{
    [DbContext(typeof(BarkodSepetimDbContext))]
    [Migration("20250525145836_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BarkodSepetim.Api.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KullaniciID");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("BarkodSepetim.Api.Models.Sepet", b =>
                {
                    b.Property<int>("SepetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SepetID"));

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("SepetID");

                    b.HasIndex("UrunID");

                    b.HasIndex("KullaniciID", "UrunID")
                        .IsUnique();

                    b.ToTable("Sepet");
                });

            modelBuilder.Entity("BarkodSepetim.Api.Models.Urun", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UrunID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("EkleyenKullaniciID")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Stok")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("UrunID");

                    b.HasIndex("Barkod")
                        .IsUnique();

                    b.HasIndex("EkleyenKullaniciID");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("BarkodSepetim.Api.Models.Sepet", b =>
                {
                    b.HasOne("BarkodSepetim.Api.Models.Kullanici", "Kullanici")
                        .WithMany("SepetUrunleri")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarkodSepetim.Api.Models.Urun", "Urun")
                        .WithMany("SepettekiUrunler")
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("BarkodSepetim.Api.Models.Urun", b =>
                {
                    b.HasOne("BarkodSepetim.Api.Models.Kullanici", "EkleyenKullanici")
                        .WithMany("EklenenUrunler")
                        .HasForeignKey("EkleyenKullaniciID");

                    b.Navigation("EkleyenKullanici");
                });

            modelBuilder.Entity("BarkodSepetim.Api.Models.Kullanici", b =>
                {
                    b.Navigation("EklenenUrunler");

                    b.Navigation("SepetUrunleri");
                });

            modelBuilder.Entity("BarkodSepetim.Api.Models.Urun", b =>
                {
                    b.Navigation("SepettekiUrunler");
                });
#pragma warning restore 612, 618
        }
    }
}
